# Generated by Django 5.1.5 on 2025-06-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('Description', models.TextField(blank=True, max_length=3500, null=True)),
            ],
        ),
    ]
