# Generated by Django 5.2.1 on 2025-06-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_categorymodel_created_at_categorymodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='Category',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
